### ISSUE TITLE
Fail to install dependencies pytest / pytest-html

### ISSUE THREAD

**Issue by MarceloSalazar** [ARMmbed/pelion-e2e-python-test-library#5]
First, I try to install this tool as indicated in the docs:

```
python setup.py bdist_wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: invalid command 'bdist_wheel'
```

Then trying to install this using install:
```python setup.py install ```

The installation fails because these two modules can't be found (besides are in requirements.txt)
- pytest
- pytest-html

So I need to manually install them using pip.

**Comment by janisimonen** [comment]
Added note to install 'wheel' before running the setup.py
